title: My Blog and Portfolio
author: Lanie Molinar
email: laniemolinar91@gmail.com
description: Welcome to Lanie Molinar's personal blog and portfolio.

# social links
twitter_username: Lanie_Molinar
github_username:  Lanie-Molinar

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
